"""add ScheduledPost model

Revision ID: 032a59692feb
Revises: 93ca2f6b5223
Create Date: 2025-04-19 15:21:00.324433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032a59692feb'
down_revision = '93ca2f6b5223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_post')
    # ### end Alembic commands ###
